config/routes.rb
Rails.application.routes.draw do
  resources :sessions, only: [:new, :create, :destroy]
  resources :users, only: [:new, :create, :show]
  resources :pictures do
    collection do
      post :confirm
    end
  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/picture.rb
class Picture < ApplicationRecord
  belongs_to :user
  mount_uploader :image, ImageUploader
end

app/models/user.rb
class User < ApplicationRecord
  has_many :pictures
  validates :name, presence: true, length: { maximum: 30 }
  validates :email, presence: true, length: { maximum: 255 },
                  format: { with: /\A[\w+\-.]+@[a-z\d\-.]+\.[a-z]+\z/i },
                  uniqueness: true
  before_validation { email.downcase!}
  has_secure_password
  validates :password, length: { minimum: 6 }
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
  include SessionsHelper
  before_action :login_required
  private
  def login_required
    redirect_to new_session_path unless current_user
  end

end

app/controllers/pictures_controller.rb
class PicturesController < ApplicationController
  def index
    @pictures = Picture.all
    @users = User.select(:id, :name)
  end
  def new
    @picture = Picture.new
  end
  def create
    @picture = Picture.new(picture_params)
    @picture.user_id = current_user.id
    if params[:back]
      render :new
    else
      if @picture.save
        redirect_to pictures_path, notice: "投稿しました"
      else
        render :new
      end
    end
  end
  def show
    @picture = Picture.find(params[:id])
  end
  def edit
    @picture = Picture.find(params[:id])
  end
  def update
    @picture = Picture.find(params[:id])
    if @picture.user_id == current_user.id
      if @picture.update(picture_params)
        redirect_to pictures_path, notice: "更新しました"
      else
        render :edit
      end
    else
      redirect_to pictures_path, notice: "権限がありません"
    end
  end
  def destroy
    @picture = Picture.find(params[:id])
    if @picture.user_id == current_user.id 
      @picture.destroy
      redirect_to pictures_path, notice: "投稿を削除しました"
    else
      redirect_to pictures_path, notice: "権限がありません"
    end
  end
  def confirm
    @picture = Picture.new(picture_params)
    @picture.user_id = current_user.id
  end
  
  private
  def picture_params
    params.require(:picture).permit(:title, :content, :image, :image_cache)
  end

end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  skip_before_action :login_required, only: [:new, :create]
  protect_from_forgery :except => [:destroy]
  def new
  end
  def create
    user = User.find_by(email: params[:session][:email].downcase)
    if user && user.authenticate(params[:session][:password])
      session[:user_id] = user.id
      redirect_to user_path(user.id)
    else
      flash.now[:danger] = 'ログインに失敗しました'
      render :new
    end
  end
  def destroy
    session.delete(:user_id)
    flash[:notice] = 'ログアウトしました'
    redirect_to new_session_path
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  skip_before_action :login_required, only: [:new, :create]
  def new
    @user = User.new
  end
  def create
    @user = User.new(users_params)
    if @user.save
      redirect_to user_path(@user.id)
    else
      render :new
    end
  end
  def show
    @user = User.find(params[:id])
  end


  private
  def users_params
    params.require(:user).permit(:name, :email, :password, :password_confirmation)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/pictures_helper.rb
module PicturesHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
  def current_user
    @current_user ||= User.find_by(id: session[:user_id])
  end
  def logged_in?
    current_user.present?
  end
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>TomodachiApp</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <header>
      <p> <strong>tomodachi</strong> book</p>
    </header>

    <% if logged_in? %>
      <%= link_to "一覧", pictures_path %>
      <%= link_to "投稿", new_picture_path %>
      <%= link_to "Profile", user_path(current_user.id) %>
      <%= link_to "Logout", session_path(current_user.id), method: :delete %>
    <% else %>
      <%= link_to "Sign up", new_user_path %>
      <%= link_to "Login", new_session_path %>
    <% end %>
    <% flash.each do |key, value| %>
      <%= content_tag(:div, value, class: "#{key}") %>
    <% end %>
    <%= yield %>
  </body>
</html>

app/views/pictures/confirm.html.erb
<h1>確認画面</h1>
<%= form_with(model: @picture, local: true ) do |pic| %>
  <%= pic.hidden_field :title %>
  <%= pic.hidden_field :content %>
  <%= pic.hidden_field :image %>
  <%= pic.hidden_field :image_cache %>
  <p>タイトル：<%= @picture.title %></p>
  <p>内容：<%= @picture.content %></p>
  <%= image_tag(@picture.image.url) %>
  <%= pic.submit "登録する" %>
  <%= pic.submit "戻る", name: 'back' %>
<% end %>

app/views/pictures/edit.html.erb
<h1>投稿の編集</h1>
<p id = "notice"><%= notice %></p>
<% if @picture.errors.any? %>
  <div id = "error_explanation">
    <h2><%= pluralize(@picture.errors.count,"error") %> prohibited this <%= @picture.name %> from being saved: </h2>
    <ul>
    <% @picture.errors.full_messages.each do |message| %>
      <li> <%= message %> </li>
    <% end %>
    </ul>
  </div>
<% end %>
<%= form_with(model: @picture, local: true) do |f| %>
  <div>
    <%= f.label :title %>
    <%= f.text_field :title %>
  </div>
  <div>
    <%= f.label :content%>
    <%= f.text_field :content %>
  </div>
  <div>
    <%= f.label :image %>
    <%= f.file_field :image %>
  </div>
  <div>
    <%= f.hidden_field :user_id %>
  </div>
  <%= f.submit "Edit" %>

<% end %>

app/views/pictures/index.html.erb
<h1>投稿一覧</h1>
<table>
  <tr>
    <th>title</th>
    <th>content</th>
    <th>name</th>
  </tr>
  <% @pictures.each do |pic| %>
  <tr>
    <td><%= pic.title %></td>
    <td><%= pic.content %></td>
    <td><%= @users.find(pic.user_id).name %></td>
    <td><%= link_to "詳細", picture_path(pic.id) %> </td>
    <td><%= link_to "編集", edit_picture_path(pic.id) if pic.user_id == current_user.id %> </td>
    <td><%= link_to "削除", picture_path(pic.id), method: :delete if pic.user_id == current_user.id %> </td>
  </tr>
  <% end %>
</table>

app/views/pictures/new.html.erb
<h1>新規投稿</h1>
<p id = "notice"><%= notice %></p>
<% if @picture.errors.any? %>
  <div id = "error_explanation">
    <h2><%= pluralize(@picture.errors.count,"error") %> prohibited this <%= @picture.name %> from being saved: </h2>
    <ul>
    <% @picture.errors.full_messages.each do |message| %>
      <li> <%= message %> </li>
    <% end %>
    </ul>
  </div>
<% end %>
<%= form_with(model: @picture, local: true, url: confirm_pictures_path ) do |f| %>
  <div>
    <%= f.label :title %>
    <%= f.text_field :title %>
  </div>
  <div>
  <%= f.label :content%>
  <%= f.text_field :content %>
  </div>
  <div>
  <%= f.label :image %>
  <%= f.file_field :image %>
  </div>
  <%= f.submit "Create" %>
  <%= f.hidden_field :image_cache %>
<% end %>

app/views/pictures/show.html.erb
<h1>投稿詳細</h1>
<p>タイトル：<%= @picture.title %></p>
<p>内容：<%= @picture.content %></p>
<%= image_tag @picture.image.url %>

app/views/users/new.html.erb
<h1>Sign up</h1>
<% if @user.errors.any? %>
  <div id = "error_explanation">
    <h2><%= pluralize(@user.errors.count,"error") %> prohibited this <%= @user.name %> from being saved: </h2>
    <ul>
    <% @user.errors.full_messages.each do |message| %>
      <li> <%= message %> </li>
    <% end %>
    </ul>
  </div>
<% end %>

<%= form_with(model: @user, local:true) do |f| %>
  <%= f.label :name %>
  <%= f.text_field :name %>
  <%= f.label :email %>
  <%= f.text_field :email %>
  <%= f.label :password %>
  <%= f.password_field :password %>
  <%= f.label :password_confirmation%>
  <%= f.password_field :password_confirmation %>
  <%= f.submit "Create my account" %>
<% end %>

app/views/users/show.html.erb
<h1><%= @user.name %>のページ</h1>
<p>メールアドレス：<%= @user.email %></p>